import { NES, Controller } from '../src/nes-core.js';
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
// Original minimal NROM program: set a background palette then loop forever.
const rom = new Uint8Array(16 + 16384 + 8192);
rom.set([78,69,83,26,1,1]);
const program=[0x78,0xa9,0x3f,0x8d,0x06,0x20,0xa9,0x00,0x8d,0x06,0x20,0xa9,0x29,0x8d,0x07,0x20,0x4c,0x10,0x80];
rom.set(program,16);
for (const offset of [0x3ffa,0x3ffc,0x3ffe]) rom.set([0,0x80],16+offset);
let frames=0;
const nes=new NES({emulateSound:false,onFrame:()=>frames++});
nes.loadROM(rom);
for(let i=0;i<5;i++)nes.frame();
assert.equal(frames,5);
nes.buttonDown(1,0);nes.buttonDown(2,1);
const saved=JSON.parse(JSON.stringify(nes.toJSON()));
nes.frame();nes.fromJSON(saved);
assert.deepEqual(nes.toJSON(),saved);
nes.frame();assert.equal(frames,7);
assert.throws(()=>new NES().loadROM(new Uint8Array(16)),/valid NES/);
const unsupported=rom.slice();unsupported[6]=0xf0;unsupported[7]=0xf0;
assert.throws(()=>new NES().loadROM(unsupported),/Unsupported mapper/);
// C/D alternate A/B while held and restore a concurrently held regular button.
const controller = new Controller();
controller.buttonDown(Controller.BUTTON_TURBO_A);
controller.buttonDown(Controller.BUTTON_TURBO_B);
controller.clock();
assert.equal(controller.state[Controller.BUTTON_A], 0x41);
assert.equal(controller.state[Controller.BUTTON_B], 0x41);
controller.clock();
assert.equal(controller.state[Controller.BUTTON_A], 0x40);
assert.equal(controller.state[Controller.BUTTON_B], 0x40);
controller.buttonDown(Controller.BUTTON_A);
controller.buttonUp(Controller.BUTTON_TURBO_A);
assert.equal(controller.state[Controller.BUTTON_A], 0x41);
controller.buttonUp(Controller.BUTTON_A);
controller.buttonUp(Controller.BUTTON_TURBO_B);
assert.equal(controller.state[Controller.BUTTON_A], 0x40);
assert.equal(controller.state[Controller.BUTTON_B], 0x40);
if(process.argv.includes('--fixture'))writeFileSync('/private/tmp/nes-club-test.nes',rom);
console.log('PASS: ROM execution, frame output, two-player input, turbo press/release, JSON save round-trip, invalid ROM and unsupported mapper');
